# Generated by Django 2.2.5 on 2020-06-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydatabase',
            name='ctc',
            field=models.IntegerField(default=0),
        ),
    ]
