# Generated by Django 2.2.5 on 2020-06-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_auto_20200612_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydatabase',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='companydatabase',
            old_name='open_true',
            new_name='open_dream',
        ),
    ]
