# Generated by Django 2.2.5 on 2020-06-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_auto_20200613_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydatabase',
            name='base',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='companydatabase',
            name='ctc',
            field=models.CharField(max_length=30),
        ),
    ]
