# Generated by Django 2.2.5 on 2020-06-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0006_auto_20200613_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydatabase',
            name='cgpa',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='companydatabase',
            name='total_offers',
            field=models.CharField(max_length=30),
        ),
    ]
