# Generated by Django 2.2.5 on 2020-06-13 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0007_auto_20200613_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydatabase',
            name='date_of_visit',
        ),
    ]
