# Generated by Django 2.2.5 on 2020-06-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0008_remove_companydatabase_date_of_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydatabase',
            name='base',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='companydatabase',
            name='cgpa',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='companydatabase',
            name='ctc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='companydatabase',
            name='total_offers',
            field=models.IntegerField(default=0),
        ),
    ]
