# Generated by Django 2.2.5 on 2020-06-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0009_auto_20200613_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydatabase',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
