# Generated by Django 2.2.5 on 2020-06-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0010_companydatabase_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
            ],
        ),
    ]
