# Generated by Django 2.2.5 on 2020-06-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0011_presentyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentyear',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
