# Generated by Django 2.2.5 on 2020-06-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0012_auto_20200613_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydatabase',
            name='year',
            field=models.FloatField(default=2020),
        ),
        migrations.AlterField(
            model_name='presentyear',
            name='year',
            field=models.FloatField(default=2020),
        ),
    ]
